### PR TITLE
Fix querycache

### LINKED ISSUE #678: Possible leak in query cache
## How query cache works
```
A

1. nses, ok := cache[query]
  * ok == false
    1. nses = registry.Find(query)
      * for nse in nses:
        1. cache[query(nse)] = nse
        2. stream := registry.Find( query(nse, Watch == true) )
        3. go B
2. return nses
```
`A.1.1.2.` results in starting a new goroutine and opening a new channel in registry to send all events related to the `nse`. 
```
B

1. nse := stream.Recv()
  * nse.Expired == true
     1. stream.Close()
     2. return
2. cache[query(nse)] = nse
```
`B.1.1.` closes registry goroutine.

## Why it can result in a goroutine leak
If registry removes `nse` in (`A.1.1.`, `A.1.1.2.`) period, channel in registry is getting opened, but there is no `nse` to produce events for this channel.

So:
1.  `B.1.` hangs on waiting for events
2.  registry goroutine hangs on waiting for `B.1.1`

### LINKED ISSUE #715: Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister is unstable
```
--- FAIL: Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister (0.45s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 56 in state select, with github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent on top of the stack:
        goroutine 56 [select]:
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent(0xc000206300, 0xc000202840, 0x15a7300, 0xc0004f8740, 0xc000206600, 0xc0001edd08, 0xe084a0)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:141 +0x12f
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).Find(0xc000206300, 0xc000202840, 0x15a7300, 0xc0004f8740, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:101 +0x367
        github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryServer).Find(0xc0004f4f00, 0xc000202840, 0x15a72a0, 0xc0004f4f30, 0x0, 0xc000088780)
        	D:/a/sdk/sdk/pkg/registry/core/next/nse_registry_server.go:62 +0x3ce
        github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient.func1(0xc0002065a0, 0x15a2320, 0xc0004f4f00, 0xc000202840, 0x15a72a0, 0xc0004f4f30)
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:128 +0xbb
        created by github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:126 +0x1b5
        
         Goroutine 55 in state chan receive, with github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv on top of the stack:
        goroutine 55 [chan receive]:
        github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv(0xc000202900, 0x15a2e60, 0xc0002028c0, 0xc000202840)
        	D:/a/sdk/sdk/pkg/registry/core/streamchannel/nse_registry_stream_channel.go:45 +0x75
        github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find.func1(0xc000202700, 0xc0002123c0, 0x27, 0xc000202840, 0x15a2f20, 0xc0004f4d20, 0x0, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:87 +0x205
        created by github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:74 +0x4db
        ]
FAIL
```

### LINKED ISSUE #728: unit test Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister have goroutines leak
Related to https://github.com/networkservicemesh/sdk/commit/20d510498cab80f1edfc44462da56403cd700f6b

## Logs
```
 Test_QueryCacheServer_ShouldCleanupGoroutinesOnNSEUnregister (0.46s)
Error:     leaks.go:78: found unexpected goroutines:
        [Goroutine 55 in state chan receive, with github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv on top of the stack:
        goroutine 55 [chan receive]:
        github.com/networkservicemesh/sdk/pkg/registry/core/streamchannel.(*networkServiceEndpointRegistryFindClient).Recv(0xc000069dc0, 0x1987000, 0xc000069d80, 0xc0004dc900)
        	D:/a/sdk/sdk/pkg/registry/core/streamchannel/nse_registry_stream_channel.go:45 +0x75
        github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find.func1(0xc0004dc7c0, 0xc0004f83f0, 0x27, 0xc0004dc900, 0x19870c0, 0xc0004d6ff0, 0x0, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:87 +0x205
        created by github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).Find
        	D:/a/sdk/sdk/pkg/registry/common/querycache/nse_client.go:74 +0x4db
        
         Goroutine 40 in state select, with github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent on top of the stack:
        goroutine 40 [select]:
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).receiveEvent(0xc0004f2480, 0xc0004dc900, 0x198b7e0, 0xc00007c8e0, 0xc000077260, 0xc000097d44, 0x5)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:141 +0x12f
        github.com/networkservicemesh/sdk/pkg/registry/common/memory.(*memoryNSEServer).Find(0xc0004f2480, 0xc0004dc900, 0x198b7e0, 0xc00007c8e0, 0x0, 0x0)
        	D:/a/sdk/sdk/pkg/registry/common/memory/nse_server.go:101 +0x367
        github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryServer).Find(0xc00007eae0, 0xc0004dc900, 0x198b780, 0xc00007eb10, 0xc000097e18, 0x5)
        	D:/a/sdk/sdk/pkg/registry/core/next/nse_registry_server.go:62 +0x3ce
        github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient.func1(0xc000077200, 0x1986480, 0xc00007eae0, 0xc0004dc900, 0x198b780, 0xc00007eb10)
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:128 +0xbb
        created by github.com/networkservicemesh/sdk/pkg/registry/core/adapters.nseFindServerToClient
        	D:/a/sdk/sdk/pkg/registry/core/adapters/nse_registry.go:126 +0x1b5
```

## Build

https://github.com/networkservicemesh/sdk/runs/1962975943

### PR DESCRIPTION
**Pull request by Bolodya1997**
# Issue
There is no expiration policy for the query cache instead of NSE unregistering.
# Solution
Add expiration time for the cache entries and update it on corresponding `Find` requests.

Closes #678.
Closes #715.
Closes #728.

### CODE REVIEW

File: pkg/networkservice/chains/nsmgr/server.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func NewServer(ctx context.Context, nsmRegistration *registryapi.NetworkServiceE
 	localBypassRegistryServer := localbypass.NewNetworkServiceEndpointRegistryServer(nsmRegistration.Url)
 
 	nseClient := next.NewNetworkServiceEndpointRegistryClient(
-		querycache.NewClient(ctx),
+		querycache.NewClient(ctx, time.Minute),
```
Comment (denis-tingaikin) [inline pkg/networkservice/chains/nsmgr/server.go:100]: Why this is not default?

File: pkg/registry/common/querycache/cache_entry.go [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+	"time"
+
+	"github.com/networkservicemesh/api/pkg/api/registry"
+)
+
+type cacheEntry struct {
+	nse            *registry.NetworkServiceEndpoint
+	expireTimeout  time.Duration
+	expirationTime time.Time
+	timer          *time.Timer
```
Comment (denis-tingaikin) [inline pkg/registry/common/querycache/cache_entry.go:30]: Why we cannot use one ticker to clean all outdated entries instead of have a timer for each entry?

**Review by denis-tingaikin — CHANGES_REQUESTED** [review]

File: pkg/networkservice/chains/nsmgr/server.go (hunk 1 above)
Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/server.go:100]: To make it unit-testable.

File: pkg/registry/common/querycache/cache_entry.go (hunk 2 above)
Comment (Bolodya1997) [reply pkg/registry/common/querycache/cache_entry.go]: Nice catch, reworked to single ticker.

File: pkg/networkservice/chains/nsmgr/server.go (hunk 1 above)
Comment (denis-tingaikin) [reply pkg/networkservice/chains/nsmgr/server.go:100]: Let's do this option.

Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/server.go]: Yep, done.

**Review by denis-tingaikin — APPROVED** [review]
