### PR TITLE
[sdk#1039] Reorder client chain elements

### LINKED ISSUE #1039: Close generated on Request from the client chain should prevent healing start
## Expected Behavior

Close generated on Request from the client chain should prevent healing start on the same hop.

## Current Behavior

1. If authorize client fails authentication, it sends Close and so after happens heal (both for pure client, server-side client).
2. If any of additional client chain elements sends Close during the request, it also causes heal start (only for server-side client).

## Steps to Reproduce

1. Start Client and wait for the token expiration.
2. Heal starts working on Client.

1. Make VPP Forwarder fail refresh Request with further remote side Close.
2. Heal starts working on Forwarder.

### PR DESCRIPTION
**Pull request by Bolodya1997**
## Description
Puts `heal` client after all other chain elements, right before `networkservice.NewNetworkServiceClient(cc)` in client, client factory chains.

Depends on https://github.com/networkservicemesh/sdk/pull/1056.

## Issue link
Closes #1039.

## How Has This Been Tested?

- [x] Added unit testing to cover
- [ ] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [x] Bug fix
- [ ] New functionallity
- [ ] Documentation
- [ ] Refactoring
- [ ] CI

### CODE REVIEW

**Review by Mixaster995 — APPROVED** [review]

File: pkg/networkservice/common/connect/server_test.go [hunk 1]
```diff
@@ -262,16 +263,22 @@ func TestConnectServer_RequestParallel(t *testing.T) {
...
 
-	assert.Equal(t, int32(parallelCount), serverClient.count)
-	assert.Equal(t, int32(parallelCount), serverA.count)
-	assert.Equal(t, int32(parallelCount), serverNext.count)
+	assert.Equal(t, int32(parallelCount), atomic.LoadInt32(&serverClient.Requests))
+	assert.Equal(t, int32(0), atomic.LoadInt32(&serverClient.Closes))
+	assert.Equal(t, int32(parallelCount), atomic.LoadInt32(&serverA.Requests))
+	assert.Equal(t, int32(0), atomic.LoadInt32(&serverA.Closes))
+	assert.Equal(t, int32(parallelCount), atomic.LoadInt32(&serverNext.Requests))
+	assert.Equal(t, int32(0), atomic.LoadInt32(&serverNext.Closes))
```
Comment (d-uzlov) [inline pkg/networkservice/common/connect/server_test.go:271]: Why do we use `assert` here (and below), instead of `require`?

Comment (Bolodya1997) [reply pkg/networkservice/common/connect/server_test.go:271]: Here we need to use `assert` before `273:    barrier.Done()`, because `require` will lead us to goroutines locked on `barrier` and so lots of errors.
But here is my fault, after this we can continue using `require` and so there is no need for any `assert`.

Fixed L276-L281 to use only `require`.

Comment (d-uzlov) [reply pkg/networkservice/common/connect/server_test.go:271]: I think it would help to add a comment about this before these asserts, to prevent people from trying to refactor it in the future.

Comment (Bolodya1997) [reply pkg/networkservice/common/connect/server_test.go:273]: Added comments near `barrier` initialization and near `barrier.Done()`.

**Review by d-uzlov — APPROVED** [review]

**Review by glazychev-art — APPROVED** [review]

**Review by denis-tingaikin — COMMENTED** [review]
Looks good. 

@Bolodya1997 Could you please move refactoring regarding to count server to separate PR.

Thanks.

**Review by denis-tingaikin — APPROVED** [review]
