### PR TITLE
Fix TestNSMGR_PassThroughLocal

### LINKED ISSUE #710: TestNSMGR_PassThroughLocal is unstable
```
    server_test.go:516: 
        	Error Trace:	server_test.go:516
        	            				server_test.go:522
        	Error:      	Received unexpected error:
        	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	            	Error returned from api/pkg/api/networkservice/networkServiceClient.Request
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:62
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/updatetoken.(*updateTokenClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/common/updatetoken/client.go:52
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer.(*injectPeerClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/utils/inject/injectpeer/client.go:62
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/utils/inject/injectpeer.(*injectPeerClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/utils/inject/injectpeer/client.go:67
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata.(*metaDataClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/utils/metadata/client.go:44
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/common/refresh/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/common/heal/client.go:77
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		/Users/user/Projects/NSM/sdk/pkg/networkservice/core/trace/client.go:58
        	Test:       	TestNSMGR_PassThroughLocal
```

### PR DESCRIPTION
**Pull request by Bolodya1997**
# Issue
`expire` timeout is too small for windows, macos - sometimes endpoint becomes unregistered.
# Solution
Increase timeout for most sandbox tests.

Closes #710

### CODE REVIEW

File: pkg/tools/sandbox/builder.go [hunk 1]
```diff
@@ -43,40 +43,41 @@ import (
 )
 
 const (
-	defaultContextTimeout = time.Second * 15
-	// DefaultRegistryExpiryDuration is a default expiry duration for registry
-	DefaultRegistryExpiryDuration = 500 * time.Millisecond
+	defaultContextTimeout         = time.Second * 15
```
Comment (denis-tingaikin) [inline pkg/tools/sandbox/builder.go:46]: Looks like I missed something
When we increased this?
It should be 1-5 sec

File: pkg/tools/sandbox/builder.go [hunk 2]
```diff
@@ -43,40 +43,41 @@ import (
...
+	defaultRegistryExpiryDuration = time.Minute
```
Comment (denis-tingaikin) [inline pkg/tools/sandbox/builder.go:47]: It is used once. Please use it inline.

File: pkg/networkservice/chains/nsmgr/server_test.go [hunk 3]
```diff
@@ -516,10 +516,13 @@ func TestNSMGR_ShouldCorrectlyAddForwardersWithSameNames(t *testing.T) {
 	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
 	defer cancel()
 
+	const registryExpiryDuration = time.Second
```
Comment (denis-tingaikin) [inline pkg/networkservice/chains/nsmgr/server_test.go:519]: Can we have a const for expire testing?

**Review by denis-tingaikin — CHANGES_REQUESTED** [review]

File: pkg/tools/sandbox/builder.go (hunk 1 above)
Comment (Bolodya1997) [reply pkg/tools/sandbox/builder.go:46]: Nope, it is an initial value from https://github.com/networkservicemesh/sdk/pull/460.

Comment (Bolodya1997) [reply pkg/tools/sandbox/builder.go:46]: Nope, it is an inital value from https://github.com/networkservicemesh/sdk/pull/460.

Comment (denis-tingaikin) [reply pkg/tools/sandbox/builder.go:46]: Oops! Let's reduce this to 5s :)

File: pkg/tools/sandbox/builder.go (hunk 2 above)
Comment (Bolodya1997) [reply pkg/tools/sandbox/builder.go:47]: It definitely would be modified in future. So it should better stay as a constant to prevent us from future searches across the file :)

File: pkg/networkservice/chains/nsmgr/server_test.go (hunk 3 above)
Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/server_test.go]: Yep, added `sandbox.RegistryExpiryDuration`.

File: pkg/tools/sandbox/builder.go (hunk 1 above)
Comment (Bolodya1997) [reply pkg/tools/sandbox/builder.go]: Reduced.

File: pkg/tools/sandbox/builder.go (hunk 2 above)
Comment (denis-tingaikin) [reply pkg/tools/sandbox/builder.go:47]: Other things like DNSDomainName and so on also declared inline in NewBuilder

Comment (Bolodya1997) [reply pkg/tools/sandbox/builder.go]: Done.

**Review by denis-tingaikin — APPROVED** [review]
