### PR TITLE
Replacing comparison of proto messages

### LINKED ISSUE #565: Do not compare protomessages via reflect.DeepEqual
## Problem

Since v1.25 proto messages contain private states. Example: https://github.com/networkservicemesh/api/blob/master/pkg/api/networkservice/connection.pb.go#L289-L291

So we should not use reflect.DeepEqual for proto messages as we do it in https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/core/trace/common.go#L59

## Steps to reproduce
```
func TestDeepEqual_PrivateProtoStates(t *testing.T) {
	p1 := new(networkservice.Path)
	p1.String()
	p2 := new(networkservice.Path)
	require.True(t, reflect.DeepEqual(p1, p2))
}
```

### PR DESCRIPTION
**Pull request by glazychev-art**
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

Fixes #565

### CODE REVIEW

File: pkg/tools/matchutils/utils.go [hunk 1]
```diff
@@ -18,29 +18,47 @@
...
 	return (left.Name == "" || strings.Contains(right.Name, left.Name)) &&
-		(left.NetworkServiceLabels == nil || reflect.DeepEqual(left.NetworkServiceLabels, right.NetworkServiceLabels)) &&
+		(left.NetworkServiceLabels == nil || labelsContains(right.NetworkServiceLabels, left.NetworkServiceLabels)) &&
 		(left.ExpirationTime == nil || left.ExpirationTime.Seconds == right.ExpirationTime.Seconds) &&
 		(left.NetworkServiceNames == nil || contains(right.NetworkServiceNames, left.NetworkServiceNames)) &&
 		(left.Url == "" || strings.Contains(right.Url, left.Url))
 }
 
-func contains(what, where []string) bool {
+func labelsContains(where, what map[string]*registry.NetworkServiceLabels) bool {
```
Comment (denis-tingajkin) [inline pkg/tools/matchutils/utils.go:45]: Could you cover this by tests?

Comment (glazychev-art) [reply pkg/tools/matchutils/utils.go:45]: Yes, new commit was added

File: pkg/tools/matchutils/utils_test.go [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+		},
+		NetworkServiceLabels: labels,
+		ExpirationTime: &timestamp.Timestamp{
+			Seconds: 500,
+			Nanos:   0,
+		},
+	}
+}
+
+func TestOneNSELabelsMatching(t *testing.T) {
```
Comment (denis-tingajkin) [inline pkg/tools/matchutils/utils_test.go:57]: Could you use memory registry server and cover this via Find API?

**Review by denis-tingajkin — APPROVED** [review]
