### PR TITLE
Pr fix connect server

### LINKED ISSUE #704: Connect server doesn't handle GRPC connection error
# Intro
If GRPC connection failes, `connect` server does nothing to make a new GRPC connection, so all subsequent requests will fail with GRPC error until `discover` find a new URL.
# Issue
If remote server restarts, healing can't recover connection without selecting a new server.
# Solution
#703

If `connect` server receives a GRPC error from client request, it deletes it. Subsequent request to this URL:
* with the same connection ID - will create a new client and continue working after 1 error received.
* with different connection ID - will receive a GRPC error, because `connInfo` still refers to the old client but will replace old client with a new one on further requests.

### PR DESCRIPTION
**Pull request by Bolodya1997**
Continues #700.
Closes #704.

### CODE REVIEW

**Review by denis-tingaikin — APPROVED** [review]

File: pkg/networkservice/common/connect/server_test.go [hunk 1]
```diff
@@ -267,6 +311,61 @@ func TestConnectServer_RequestParallel(t *testing.T) {
...
+	// 1. Create connectServer
+
+	s := connect.NewServer(context.TODO(),
+		func(_ context.Context, cc grpc.ClientConnInterface) networkservice.NetworkServiceClient {
+			return injecterror.NewClient()
+		},
+		grpc.WithInsecure(),
+	)
+
+	func() {
```
Comment (denis-tingaikin) [inline pkg/networkservice/common/connect/server_test.go:326]: This function looks strange.

@Bolodya1997 Could we also remove this function and call `goleak.VerifyNone` in line 361?

File: pkg/networkservice/common/connect/server_test.go [hunk 2]
```diff
@@ -267,6 +311,61 @@ func TestConnectServer_RequestParallel(t *testing.T) {
...
+		ctx, cancel := context.WithCancel(context.Background())
+		defer cancel()
+
+		// 2. Setup servers
+
+		urlA := &url.URL{Scheme: "tcp", Host: "127.0.0.1:10000"}
```
Comment (denis-tingaikin) [inline pkg/networkservice/common/connect/server_test.go:332]: Let's do not hardcode port

Comment (Bolodya1997) [reply pkg/networkservice/common/connect/server_test.go]: Fixed.

File: pkg/networkservice/common/connect/server_test.go (hunk 1 above)
Comment (Bolodya1997) [reply pkg/networkservice/common/connect/server_test.go]: Yep, fixed.

**Review by denis-tingaikin — APPROVED** [review]

**Comment by denis-tingaikin** [comment]
@edwarnicke Could you take a look at this patch that's solve issue https://github.com/networkservicemesh/sdk/issues/704?

Any thoughts are welcome :)

**Comment by denis-tingaikin** [comment]
@edwarnicke , @Bolodya1997 I think this also can be simplified if we will use refcountmap that allows to delete entry not look at ref count. What do you think?

**Review by artem-belov — APPROVED** [review]

File: pkg/networkservice/common/clienturl/client.go [hunk 3]
```diff
@@ -75,11 +75,16 @@ func (u *clientURLClient) init() error {
 			u.dialErr = errors.New("cannot dial nil clienturl.ClientURL(ctx)")
 			return
 		}
+
+		ctx, cancel := context.WithTimeout(u.ctx, dialTimeout)
```
Comment (edwarnicke) [inline pkg/networkservice/common/clienturl/client.go:79]: Why are we introducing a new arbitrary dialTimeout instead of deriving it from the ctx of the request?

File: pkg/networkservice/common/connect/server.go [hunk 4]
```diff
@@ -94,60 +125,67 @@ func (s *connectServer) Close(ctx context.Context, conn *networkservice.Connecti
...
+	<-s.executor.AsyncExec(clientURL.String(), func() {
+		// Fast path if we already have client for the clientURL and we chould not reconnect, use it.
+		var loaded bool
+		client, loaded = s.clients.Load(clientURL.String())
+		if !loaded {
+			// If not, create and LoadOrStore a new one.
+			client = s.newClient(clientURL)
+			s.clients.Store(clientURL.String(), client)
+		}
+		client.count++
```
Comment (edwarnicke) [inline pkg/networkservice/common/connect/server.go:156]: Why are we blocking globally when we could do something fairly straightforward and non-blocking like:

```suggestion
		for {
			// Create a client
			client = s.newClient(clientURL)
			atomic.AddInt64(&client.count,1)
			var loaded bool
			// Load or store the client
			client, loaded = s.clients.LoadOrStore(clientURL.String(),client)
			// If its loaded and incrementing the counter from 0... somebodies already deleted it, so try again
			if loaded && atomic.AddInt64(&client.count,1) > 1 {
				continue
			}
		}
```

File: pkg/networkservice/common/connect/server.go [hunk 5]
```diff
@@ -94,60 +125,67 @@ func (s *connectServer) Close(ctx context.Context, conn *networkservice.Connecti
...
+func (s *connectServer) closeClient(client *clientInfo, clientURL string) {
+	<-s.executor.AsyncExec(clientURL, func() {
+		client.count--
+		if client.count == 0 {
+			if loadedClient, ok := s.clients.Load(clientURL); ok && client == loadedClient {
+				s.clients.Delete(clientURL)
+			}
+			client.onClose()
+		}
+	})
```
Comment (edwarnicke) [inline pkg/networkservice/common/connect/server.go:181]: Could be made non-blocking with something like:

```suggestion
	if atomic.AddInt64(&client.count,-1) == 0 {
		client,ok := s.clients.LoadAndDelete(clientURL)
		if ok {
			client.onClose()
		}
	}
```

File: pkg/networkservice/common/connect/server.go [hunk 6]
```diff
@@ -65,22 +74,44 @@ func NewServer(
...
 	if err != nil {
+		if _, ok := s.connInfos.Load(request.GetConnection().GetId()); !ok {
+			s.closeClient(clientInfo, clientURL.String())
+		}
+
+		// Close current client chain if grpc connection was closed
+		if grpcutils.UnwrapCode(err) == codes.Canceled {
+			s.deleteClient(clientInfo, clientURL.String())
+			s.connInfos.Delete(request.GetConnection().GetId())
+		}
```
Comment (edwarnicke) [inline pkg/networkservice/common/connect/server.go:93]: Just because we get a codes.Canceled ... doesn't mean anything about the *client* ... it only tells you about the *connection*

File: pkg/networkservice/common/serialize/client.go [hunk 7]
```diff
@@ -25,10 +25,11 @@ import (
 	"github.com/networkservicemesh/api/pkg/api/networkservice"
 
 	"github.com/networkservicemesh/sdk/pkg/networkservice/core/next"
+	"github.com/networkservicemesh/sdk/pkg/tools/multiexecutor"
 )
 
 type serializeClient struct {
-	executor multiExecutor
+	executor multiexecutor.MultiExecutor
```
Comment (edwarnicke) [inline pkg/networkservice/common/serialize/client.go:32]: This feels like a separate PR to introduce multiexecutor into serialize.  Could we split it out?

**Comment by edwarnicke** [comment]
One way or the other, we need to find a way to *not* be queueing up all Requests/Closes globally in connect.  Its fine to queue them up by Connection.ID... but not globally.  I think we can get there with a combination of sync.Map and atomics.

File: pkg/networkservice/common/connect/server.go (hunk 6 above)
Comment (artem-belov) [reply pkg/networkservice/common/connect/server.go:93]: @edwarnicke That is the point, we want to close client if something wrong with connection. Right now if grpc connection is broken, we just fail all requests comming to this client and doing nothing to reconnect.

Comment (edwarnicke) [reply pkg/networkservice/common/connect/server.go:93]: Doesn't codes.Canceled mean something is wrong with the *request* not the *connection*?  I presume it comes back if the ctx for the request exceeds its timeout for example...

File: pkg/networkservice/common/connect/server.go (hunk 4 above)
Comment (edwarnicke) [reply pkg/networkservice/common/connect/server.go:156]: Ah... I'd missed that this was the multiexecutor and thus per clientURL and not global.  This is fine as written.

File: pkg/networkservice/common/connect/server.go (hunk 5 above)
Comment (edwarnicke) [reply pkg/networkservice/common/connect/server.go:181]: Ah... I'd missed that this was the multiexecutor and thus per clientURL and not global. This is fine as written.

File: pkg/networkservice/common/connect/server.go (hunk 6 above)
Comment (edwarnicke) [reply pkg/networkservice/common/connect/server.go:93]: I still suspect this will unnecessarily cycle connections when we don't need to... However, the blast radius should be fine.  Let's move on :)

File: pkg/networkservice/common/clienturl/client.go (hunk 3 above)
Comment (Bolodya1997) [reply pkg/networkservice/common/clienturl/client.go:80]: It will break discover + roundrobin, because it will wait for the first dial until requests lives and so there won't be any chance to try someone else.
