### PR TITLE
fix: kernel client should not add new mechanism if kernel mechanism already added into preference list

### LINKED ISSUE #721: mechanisms/clients should not duplicate preference mechanisms
## Issue

If any of our client {vfio, memif, [kernel](https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/common/mechanisms/kernel/client.go#L38)} that appends mechanisms  will be used with some prepared request that already contains mechanisms in the preference list then mechanisms count of the mechanism type will be increased on 1

Also, this can be important for refresh scenarios.

## Solution

If the request already has the needed mechanism then just modify it and do not add a new mechanism.

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

This PR fixes kernel client for #721

### CODE REVIEW

**Review by fkautz — APPROVED** [review]

File: pkg/networkservice/common/mechanisms/kernel/client.go [hunk 1]
```diff
@@ -44,23 +46,40 @@ func NewClient(options ...Option) networkservice.NetworkServiceClient {
...
+// updateMechanismPreferences returns true if MechanismPreferences has updated
+func updateMechanismPreferences(request *networkservice.NetworkServiceRequest) bool {
+	var updated = false
+
+	for _, m := range request.GetRequestMechanismPreferences() {
+		if m.Type == kernel.MECHANISM {
+			if m.Parameters == nil {
+				m.Parameters = make(map[string]string)
+			}
+			m.Parameters[kernel.NetNSURL] = (&url.URL{Scheme: "file", Path: netNSFilename}).String()
```
Comment (haiodo) [inline pkg/networkservice/common/mechanisms/kernel/client.go:75]: Should we add kernel.InterfaceNameKey with k.interfaceName?

Comment (denis-tingaikin) [reply pkg/networkservice/common/mechanisms/kernel/client.go:78]: yes, we should, fixed.

**Review by haiodo — APPROVED** [review]
