### PR TITLE
Fix timeouts in heal tests

### LINKED ISSUE #840: Restore heal tests are unstable
https://github.com/networkservicemesh/sdk/runs/2359524584?check_suite_focus=true#step:5:107
https://github.com/networkservicemesh/sdk/runs/2359207410?check_suite_focus=true#step:5:182

## Issues
Small token timeout sometimes causes not expected refresh Request and this causes the following issues:
1. Extra Requests in count server.
2. If hop dies during processing Request, it causes multiple `connectClient` being deleted all across the hops chain (#808) and so extra Closes/Requests in count server.

### LINKED ISSUE #845: Forwarder heal tests are unstable
## Failure Logs
https://github.com/networkservicemesh/sdk/runs/2378624756?check_suite_focus=true#step:5:125
```
--- FAIL: TestNSMGR_HealLocalForwarder (10.03s)
    server_heal_test.go:230: 
        	Error Trace:	server_heal_test.go:230
        	            				server_heal_test.go:142
        	Error:      	Received unexpected error:
        	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	            	Error returned from api/pkg/api/networkservice/networkServiceClient.Request
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:62
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/authorize.(*authorizeClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/authorize/client.go:53
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata.(*metaDataClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/utils/metadata/client.go:44
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/refresh/client.go:56
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/heal/client.go:48
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/serialize.(*serializeClient).Request.func1
        	            		D:/a/sdk/sdk/pkg/networkservice/common/serialize/client.go:45
        	            	github.com/networkservicemesh/sdk/pkg/tools/multiexecutor.(*MultiExecutor).AsyncExec.func2.1
        	            		D:/a/sdk/sdk/pkg/tools/multiexecutor/multi_executor.go:54
        	            	github.com/edwarnicke/serialize.(*Executor).process
        	            		C:/Users/runneradmin/go/pkg/mod/github.com/edwarnicke/serialize@v1.0.7/serialize.go:68
        	Test:       	TestNSMGR_HealLocalForwarder
```

https://github.com/networkservicemesh/sdk/runs/2378343352?check_suite_focus=true#step:5:140
```
--- FAIL: TestNSMGR_HealRemoteForwarder (10.04s)
    server_heal_test.go:228: 
        	Error Trace:	server_heal_test.go:228
        	            				server_heal_test.go:173
        	Error:      	Received unexpected error:
        	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	            	Error returned from api/pkg/api/networkservice/networkServiceClient.Request
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:62
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/authorize.(*authorizeClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/authorize/client.go:53
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata.(*metaDataClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/utils/metadata/client.go:44
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh.(*refreshClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/refresh/client.go:56
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/heal.(*healClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/common/heal/client.go:48
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*beginTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:58
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:69
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.(*endTraceClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/trace/client.go:99
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/core/next.(*nextClient).Request
        	            		D:/a/sdk/sdk/pkg/networkservice/core/next/client.go:71
        	            	github.com/networkservicemesh/sdk/pkg/networkservice/common/serialize.(*serializeClient).Request.func1
        	            		D:/a/sdk/sdk/pkg/networkservice/common/serialize/client.go:45
        	            	github.com/networkservicemesh/sdk/pkg/tools/multiexecutor.(*MultiExecutor).AsyncExec.func2.1
        	            		D:/a/sdk/sdk/pkg/tools/multiexecutor/multi_executor.go:54
        	            	github.com/edwarnicke/serialize.(*Executor).process
        	            		C:/Users/runneradmin/go/pkg/mod/github.com/edwarnicke/serialize@v1.0.7/serialize.go:68
        	Test:       	TestNSMGR_HealRemoteForwarder
```

### PR DESCRIPTION
**Pull request by Bolodya1997**
Closes #845.
Closes #840.

## Description
1. 1 second timeout sometimes is not enough to perform a Request, so it should be increased.
2. For restore tests token shouldn't expire because we expect hop to be restored.

### CODE REVIEW

File: pkg/networkservice/chains/nsmgr/heal_test.go [hunk 1]
```diff
@@ -465,9 +439,16 @@ func TestNSMGR_CloseHeal(t *testing.T) {
 	require.NoError(t, ctx.Err())
 }
 
+func tokenTimeout(restored bool) time.Duration {
+	if restored {
+		return time.Hour
+	}
+	return 3 * time.Second
+}
```
Comment (denis-tingaikin) [inline pkg/networkservice/chains/nsmgr/heal_test.go:447]: This adding complexity, please use constants.

Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/heal_test.go]: Yep, fixed.

File: pkg/networkservice/chains/nsmgr/heal_test.go [hunk 2]
```diff
@@ -113,65 +118,57 @@ func testNSMGRHealEndpoint(t *testing.T, restored bool) {
 }
 
 func TestNSMGR_HealLocalForwarder(t *testing.T) {
-	t.Skip("https://github.com/networkservicemesh/sdk/issues/845")
-
-	forwarderCtx, forwarderCtxCancel := context.WithTimeout(context.Background(), time.Second)
+	forwarderCtx, forwarderCtxCancel := context.WithCancel(context.Background())
```
Comment (denis-tingaikin) [inline pkg/networkservice/chains/nsmgr/heal_test.go:121]: Why do we need to remove test timeouts from the root context?

Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/heal_test.go:121]: Because we manually close the hop to heal when we need it. We have a global timeout for the test, so it wouldn't last forever - this timeout makes no sense at all.

Comment (denis-tingaikin) [reply pkg/networkservice/chains/nsmgr/heal_test.go:121]: The current global timeout is 5m.
We expect that sandbox test should pass during 5s.
So current heal tests could pass in 2-3min and be valid when it is not.

Comment (Bolodya1997) [reply pkg/networkservice/chains/nsmgr/heal_test.go:121]: My fault, it is not quite clear, but I have meant this as a _global timeout_:
https://github.com/networkservicemesh/sdk/blob/c06e6f43c17c183b4a1e77b984c01d17f3d5e734/pkg/networkservice/chains/nsmgr/heal_test.go#L180
And so it is only `10s` for the test. So we have `5s` (or less) for the request before healing and rest of the time for the requests after healing.

Comment (denis-tingaikin) [reply pkg/networkservice/chains/nsmgr/heal_test.go:121]: ok, got it

**Review by denis-tingaikin — APPROVED** [review]
